name: Prevent unauthorized workflows
on:
  pull_request_target:
    paths:
      - ".github/workflows/**"
jobs:
    check-author:
      runs-on: ubuntu-latest
      permissions:
        contents: read
        pull-requests: read
      steps:
        - name: Check if PR author is authorized
          id: plan
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            AUTHOR=$(jq -r '.sender.login' $GITHUB_EVENT_PATH)
            MEMBERS='sandeep'
            
            if [[ ! " $MEMBERS " =~ " $AUTHOR " ]]; then
              echo "Only members of the '$ALLOWED_TEAM' team can create or modify workflow files."
              exit 1
            fi

            echo "$AUTHOR is authorized to modify workflow files"
